== Devops

This module is intended to contain several deployment strategies for the produced images.

=== Prerequisites

* KVM
* Git
* https://docs.okd.io/latest/cli_reference/get_started_cli.html#installing-the-cli[OC client]
* https://linkerd.io/2/getting-started/[Linkerd client] (not yet used beside install-script)

`KVM` is used as Hypervisor because it is included in the Linux-Kernel. Futhermore `Vagrant` is used to
easily setup and destroy an environment.

All environments will provide an internal DNS to have full control over the domains in the subnet `vnet.de`, including wildcards.

NOTE: The follwing setup was taken from this https://liquidat.wordpress.com/2017/03/03/howto-automated-dns-resolution-for-kvmlibvirt-guests-with-a-local-domain/[Blogpost]
and all manual steps were converted into a `Vagrantfile`.

In order to resolve DNS entries within the subnet `vnet.de` the local NetworkManager must be enhanced with an
additional dnsmasq-instance and forward certain lookups into the subnet

.enable dnsmasq in local NetworkManager
[source, sh]
----
$ cat /etc/NetworkManager/conf.d/localdns.conf
[main]
dns=dnsmasq
----

.forward all lookups for *.vnet.de to the DNS inside the subnet
[source, sh]
----
$ cat /etc/NetworkManager/dnsmasq.d/vnet.conf
server=/vnet.de/192.168.60.100
----


TIP: when changing the network-settings in the Vagrantfile after a subnet has already been created, the existing
KVM network must be deleted. Otherwise the changes wont be applied.


=== Openshift Kubernetes Distribution OKD

OKD is the fully fledged Kubernetes Distribution by RedHat, which by default secures many aspects in the
Kubernetes cluster and provides additional features.

The `openshift` folder contains a Vagrant environment which can host a fully functioning domain of several
nodes:

* domain.vnet.de
** DNS-Server for the cluster
** NFS-Server which can be added as persistent-volume to OKD
* master.vnet.de
** web-console available at https://openshift.vnet.de:8443
** ETCD for cluster-configuration
* infra.vnet.de - all OKD infrastructure-components will be installed here
** Image Registry
** Router
** ...
* app-1.vnet.de
* app-2.vnet.de
** Compute nodes for applications

==== Install OKD

Run `openshift/install.sh` which will create the environment and run the https://github.com/openshift/openshift-ansible[openshift-ansible installer]

[source,sh]
----
include::openshift/install.sh[]
----

NOTE: the installer is always in flux, hence a at least known to work tag will be checked out.


==== Use OKD

* Run `vagrant up` from the openshift-folder (if the cluster is not already running)
* Access https://openshift.vnet.de:8443
