[quote, Isaac Asimov]
> Self-education is, I firmly believe, the only kind of education there is.

== Purpose

This repository is mainly for personal education, developing the same
domain in different languages/frameworks. Another goal is to see which
difficulties aries in a microservice architecture (distributed system)

== Domain

The following picture is just a rough explanation about the services and their purpose.


[ditaa]
....

                             /----------------\                   /-------\
                             |                |                   |       |
                             |     Bikes      | <-----------------+       |
                             |                |                   |       |
                             \--------+-------/                   |   O   |
                                      |                           |   r   |
                                      | Event (New Bike)          |   c   |
                                      v                           |   h   |
                                                                  |   e   |
/------------\         +--------------------------+               |   s   |
|            |         |                          |               |   t   |
|  Testing   | <-------+    Messaging (Kafka)     +-------------> |   r   |
|            |         |                          |               |   a   |
\------------/         +--------------------------+               |   t   |
                                                                  |   i   |
                                      ^                           |   o   |
                                      | Event (Approved/Declined) |   n   |
                                      |                           |       |
                             /----------------\                   |       |
                             |                |                   |       |
                             |  Wife + Rules  | <-----------------+       |
                             |                |                   |       |
                             \--------+-------/                   \-------/


....

Short step-by-step explanation

. add a new Bike
.. the bike-service creates the bike, with a pending approval state
.. modification is not allowed until approved
. request approval from the wife-domain
** decides with some simple rules if the request is to be approved
** depending on the language this might be something more advanced (e.g. Drools as a rules engine)
. change state according to approval

IMPORTANT: I advice against using an orchestration-layer in the way of a
enterprise-process spanning multiple domains. Instead use messaging for
crossing the boundaries, while using orchestration (like BPMN) within a
bounded context if necessary. Using an process which is not owned by the team
responsible for the domain, introduces a bottleneck (development/release-cycle)

== Languages / Frameworks / Tools

The plan is to implement several services in the following languages/frameworks

* JavaEE
* Rust
* Go
* Scala (using Akka)

Orchestration is done with the following.

* Camunda (just using a pseudo-process)
* Akka

TIP: Both orchestrations can be used at the same time, because the Kafka consumers use
the same consumer-group with a round-robin partition-assignment-strategy.

=== Tooling

* Hiptest for acceptance-tests
* Docker
* Kubernetes


=== Protobuf

The Request/Response values are generated via Protocol-Buffers because it allows generation based on an IDL.
The schema is shared between all used languages/frameworks. In addition Protobuf allows the values to be parsed from, and written to
either binary-format or JSON which is pretty handy (binary is fast, and JSON nice for Browsers and humans to debug).



link:README-SERVICES.adoc[Readme-Services]