
CREATE TABLE Bike
(
  ID           SERIAL NOT NULL,
  APPROVAL     INTEGER,
  CREATED      TIMESTAMP,
  MANUFACTURER VARCHAR(255),
  NAME         VARCHAR(255),
  UPDATED      TIMESTAMP,
  VALUE        FLOAT,
  WEIGHT       FLOAT,
  PRIMARY KEY (ID)
);

CREATE TABLE Bike_Parts
(
  NAME    VARCHAR(255),
  WEIGHT  FLOAT,
  Bike_ID BIGINT
);

ALTER TABLE Bike_Parts
  ADD CONSTRAINT FK_Bike_Parts_Bike_ID FOREIGN KEY (Bike_ID) REFERENCES BIKE (ID);




