CREATE SEQUENCE BIKES_SEQ INCREMENT BY 50 START WITH 50 NO CYCLE CACHE 50;

CREATE TABLE Bike
(
    ID           BIGINT DEFAULT nextval('bikes_seq') NOT NULL,
    VERSION      BIGINT,
    CREATED      TIMESTAMP,
    UPDATED      TIMESTAMP,
    APPROVAL     CHAR(1),
    MANUFACTURER VARCHAR(255),
    NAME         VARCHAR(255),
    VALUE        FLOAT,
    WEIGHT       FLOAT,
    PRIMARY KEY (ID)
);

CREATE TABLE Bike_Parts
(
  NAME    VARCHAR(255),
  WEIGHT  FLOAT,
  Bike_ID BIGINT
);

ALTER TABLE Bike_Parts
  ADD CONSTRAINT FK_Bike_Parts_Bike_ID FOREIGN KEY (Bike_ID) REFERENCES BIKE (ID);




