---
- hosts: all
  become: yes
  tasks:
  - name: Install basic packages
    yum: 
      name="{{ packages }}"
      state=present
    vars:
      packages:
        - ntp
        - NetworkManager-tui
        - bind-utils
        - net-tools
        - nmap
        - nc
  - name: Upgrade all packages
    yum: name=* state=latest
  - name: Ensure NTPD is running.
    service: name=ntpd state=started enabled=yes
# Following only on domain
  - name: Install dnsmasq service.
    yum: name=dnsmasq state=present
    when: "'domain' in inventory_hostname"
  - name: Ensure dnsmasq is running.
    service: name=dnsmasq state=started enabled=yes 
    when: "'domain' in inventory_hostname"
  - name: Configure DHCP/DNS for dnsmasq
    copy:
      src: resources/vnet.conf
      dest: /etc/dnsmasq.d/vnet.conf
    when: "'domain' in inventory_hostname"
  - name: Restart dnsmasq
    service: name=dnsmasq state=restarted
    when: "'domain' in inventory_hostname"
# Following for all, except domain
  - name: Add gateway to eth1
    shell: nmcli c modify "System eth1" ipv4.gateway "192.168.60.1" ipv4.dns "192.168.60.100" ipv4.dns-search "vnet.de"
    when: "'domain' not in inventory_hostname"
  - name: change hosts
    copy:
      src: resources/hosts
      dest: /etc/hosts
    when: "'domain' not in inventory_hostname"
  - name: Restart NetworkManager
    service: name=network state=restarted
    when: "'domain' not in inventory_hostname"
