---
- hosts: master
  become: yes
  tasks:
  - name: Copy Openshift definitions
    copy:
      src: resources/persistent-volume.yml
      dest: /home/vagrant/persistent-volume.yml
  - name: Create PV
    command: "{{item}}"
    with_items:
      - 'oc login -u system:admin'
      - 'oc create -f /home/vagrant/persistent-volume.yml'
