CREATE SEQUENCE WIFE_SEQ INCREMENT BY 50 START WITH 50 NO CYCLE CACHE 50;

CREATE TABLE BikeApproval
(
  ID       BIGINT DEFAULT nextval('wife_seq') NOT NULL,
  APPROVAL CHAR(1),
  BIKEID   BIGINT,
  CREATED  TIMESTAMP,
  UPDATED  TIMESTAMP,
  VALUE    FLOAT,
  PRIMARY KEY (ID)
);



