// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package wife.infrastructure.protobuf

object WifeProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_]] = Seq(
    wife.infrastructure.protobuf.BikeApprovalsMessage,
    wife.infrastructure.protobuf.BikeApprovalMessage,
    wife.infrastructure.protobuf.CreateBikeApprovalMessage,
    wife.infrastructure.protobuf.BikeApprovedMessage,
    wife.infrastructure.protobuf.BikeRejectedMessage
  )
  private lazy val ProtoBytes: Array[Byte] =
    scalapb.Encoding.fromBase64(scala.collection.Seq(
      """ChlzcmMvbWFpbi9wcm90by93aWZlLnByb3RvEgR3aWZlIk8KFEJpa2VBcHByb3ZhbHNNZXNzYWdlEjcKCWFwcHJvdmFscxgBI
  AMoCzIZLndpZmUuQmlrZUFwcHJvdmFsTWVzc2FnZVIJYXBwcm92YWxzIngKE0Jpa2VBcHByb3ZhbE1lc3NhZ2USFwoHYmlrZV9pZ
  BgBIAEoA1IGYmlrZUlkEhQKBXZhbHVlGAIgASgCUgV2YWx1ZRIyCghhcHByb3ZhbBgDIAEoDjIWLndpZmUuQXBwcm92YWxFbnVtV
  HlwZVIIYXBwcm92YWwiSgoZQ3JlYXRlQmlrZUFwcHJvdmFsTWVzc2FnZRIXCgdiaWtlX2lkGAEgASgDUgZiaWtlSWQSFAoFdmFsd
  WUYAiABKAJSBXZhbHVlIi4KE0Jpa2VBcHByb3ZlZE1lc3NhZ2USFwoHYmlrZV9pZBgBIAEoA1IGYmlrZUlkIi4KE0Jpa2VSZWplY
  3RlZE1lc3NhZ2USFwoHYmlrZV9pZBgBIAEoA1IGYmlrZUlkKjsKEEFwcHJvdmFsRW51bVR5cGUSCwoHUEVORElORxAAEgwKCEFDQ
  0VQVEVEEAESDAoIUkVKRUNURUQQAkIuChx3aWZlLmluZnJhc3RydWN0dXJlLnByb3RvYnVmWg5pbmZyYXN0cnVjdHVyZWIGcHJvd
  G8z"""
    ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, Array(
    ))
  }

  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}