version: '3.2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka:1.1.0
    container_name: kafka
    hostname: kafka
    ports:
      # use dynamic ports - "9092" when scaling to multiple nodes
      - 9092:9092
    environment:
      # explicitly set hostname when scaling to multiple nodes
      KAFKA_ADVERTISED_HOST_NAME: ${DOCKER_HOST_IP:-127.0.0.1}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_CREATE_TOPICS: "language-pit.events:1:1"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock

  orchestration:
    image: languagepit/orchestration:akka
    depends_on:
      - kafka
    hostname: "orchestration-akka"
    ports:
      - 9090:9090
    environment:
      BIKE_HOST: bike
      WIFE_HOST: wife

  bike:
    image: languagepit/javaee-bikes:openliberty
    depends_on:
      - orchestration
    ports:
      - 8080:8080
    environment:
      KAFKA_HOST: ${DOCKER_HOST_IP:-127.0.0.1}
      KAFKA_PORT: 9092
      KAFKA_EVENT_TOPIC: "language-pit.events"
      DERBY_DB_LOCATION: "/opt/wife-db"
      ORCHESTRATION_URL: "http://orchestration-akka:9090/"

  wife:
    image: languagepit/javaee-wife:openliberty
    depends_on:
      - orchestration
    ports:
      - 8090:8080
    environment:
      KAFKA_HOST: ${DOCKER_HOST_IP:-127.0.0.1}
      KAFKA_PORT: 9092
      KAFKA_EVENT_TOPIC: "language-pit.events"
      DERBY_DB_LOCATION: "/opt/bikes.db"
      ORCHESTRATION_URL: "http://orchestration-akka:9090/"

