// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package bikes.infrastructure.protobuf

@SerialVersionUID(0L)
final case class BikesMessage(
                               bikes: _root_.scala.collection.Seq[_root_.bikes.infrastructure.protobuf.BikeMessage] = _root_.scala.collection.Seq.empty
                             ) extends scalapb.GeneratedMessage with scalapb.Message[BikesMessage] with scalapb.lenses.Updatable[BikesMessage] {
  @transient
  private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0

  private[this] def __computeSerializedValue(): _root_.scala.Int = {
    var __size = 0
    bikes.foreach(bikes => __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(bikes.serializedSize) + bikes.serializedSize)
    __size
  }

  final override def serializedSize: _root_.scala.Int = {
    var read = __serializedSizeCachedValue
    if (read == 0) {
      read = __computeSerializedValue()
      __serializedSizeCachedValue = read
    }
    read
  }

  def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): Unit = {
    bikes.foreach { __v =>
      _output__.writeTag(1, 2)
      _output__.writeUInt32NoTag(__v.serializedSize)
      __v.writeTo(_output__)
    };
  }

  def mergeFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): _root_.bikes.infrastructure.protobuf.BikesMessage = {
    val __bikes = (_root_.scala.collection.immutable.Vector.newBuilder[_root_.bikes.infrastructure.protobuf.BikeMessage] ++= this.bikes)
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __bikes += _root_.scalapb.LiteParser.readMessage(_input__, _root_.bikes.infrastructure.protobuf.BikeMessage.defaultInstance)
        case tag => _input__.skipField(tag)
      }
    }
    _root_.bikes.infrastructure.protobuf.BikesMessage(
      bikes = __bikes.result()
    )
  }

  def clearBikes = copy(bikes = _root_.scala.collection.Seq.empty)

  def addBikes(__vs: _root_.bikes.infrastructure.protobuf.BikeMessage*): BikesMessage = addAllBikes(__vs)

  def addAllBikes(__vs: TraversableOnce[_root_.bikes.infrastructure.protobuf.BikeMessage]): BikesMessage = copy(bikes = bikes ++ __vs)

  def withBikes(__v: _root_.scala.collection.Seq[_root_.bikes.infrastructure.protobuf.BikeMessage]): BikesMessage = copy(bikes = __v)

  def getFieldByNumber(__fieldNumber: _root_.scala.Int): scala.Any = {
    (__fieldNumber: @_root_.scala.unchecked) match {
      case 1 => bikes
    }
  }

  def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
    require(__field.containingMessage eq companion.scalaDescriptor)
    (__field.number: @_root_.scala.unchecked) match {
      case 1 => _root_.scalapb.descriptors.PRepeated(bikes.map(_.toPMessage)(_root_.scala.collection.breakOut))
    }
  }

  def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)

  def companion = _root_.bikes.infrastructure.protobuf.BikesMessage
}

object BikesMessage extends scalapb.GeneratedMessageCompanion[bikes.infrastructure.protobuf.BikesMessage] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[bikes.infrastructure.protobuf.BikesMessage] = this

  def fromFieldsMap(__fieldsMap: scala.collection.immutable.Map[_root_.com.google.protobuf.Descriptors.FieldDescriptor, scala.Any]): bikes.infrastructure.protobuf.BikesMessage = {
    require(__fieldsMap.keys.forall(_.getContainingType() == javaDescriptor), "FieldDescriptor does not match message type.")
    val __fields = javaDescriptor.getFields
    bikes.infrastructure.protobuf.BikesMessage(
      __fieldsMap.getOrElse(__fields.get(0), Nil).asInstanceOf[_root_.scala.collection.Seq[_root_.bikes.infrastructure.protobuf.BikeMessage]]
    )
  }

  implicit def messageReads: _root_.scalapb.descriptors.Reads[bikes.infrastructure.protobuf.BikesMessage] = _root_.scalapb.descriptors.Reads {
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
      bikes.infrastructure.protobuf.BikesMessage(
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.collection.Seq[_root_.bikes.infrastructure.protobuf.BikeMessage]]).getOrElse(_root_.scala.collection.Seq.empty)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }

  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = BikesProto.javaDescriptor.getMessageTypes.get(0)

  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = BikesProto.scalaDescriptor.messages(0)

  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 1 => __out = bikes.infrastructure.protobuf.BikeMessage
    }
    __out
  }

  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_]] = Seq.empty

  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)

  lazy val defaultInstance = bikes.infrastructure.protobuf.BikesMessage(
  )

  implicit class BikesMessageLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, bikes.infrastructure.protobuf.BikesMessage]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, bikes.infrastructure.protobuf.BikesMessage](_l) {
    def bikes: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.collection.Seq[_root_.bikes.infrastructure.protobuf.BikeMessage]] = field(_.bikes)((c_, f_) => c_.copy(bikes = f_))
  }

  final val BIKES_FIELD_NUMBER = 1
}
