// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package bikes.infrastructure.protobuf

object BikesProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_]] = Seq(
    bikes.infrastructure.protobuf.BikesMessage,
    bikes.infrastructure.protobuf.BikeMessage,
    bikes.infrastructure.protobuf.CreateBikeMessage,
    bikes.infrastructure.protobuf.PartType,
    bikes.infrastructure.protobuf.ApprovalMessage,
    bikes.infrastructure.protobuf.BikeCreatedMessage,
    bikes.infrastructure.protobuf.BikeDeletedMessage
  )
  private lazy val ProtoBytes: Array[Byte] =
    scalapb.Encoding.fromBase64(scala.collection.Seq(
      """ChpzcmMvbWFpbi9wcm90by9iaWtlcy5wcm90bxIFYmlrZXMiOAoMQmlrZXNNZXNzYWdlEigKBWJpa2VzGAEgAygLMhIuYmlrZ
  XMuQmlrZU1lc3NhZ2VSBWJpa2VzIs8BCgtCaWtlTWVzc2FnZRIiCgxtYW51ZmFjdHVyZXIYASABKAlSDG1hbnVmYWN0dXJlchISC
  gRuYW1lGAIgASgJUgRuYW1lEhYKBndlaWdodBgDIAEoAlIGd2VpZ2h0EhQKBXZhbHVlGAQgASgCUgV2YWx1ZRIlCgVwYXJ0cxgFI
  AMoCzIPLmJpa2VzLlBhcnRUeXBlUgVwYXJ0cxIzCghhcHByb3ZhbBgGIAEoDjIXLmJpa2VzLkFwcHJvdmFsRW51bVR5cGVSCGFwc
  HJvdmFsIqABChFDcmVhdGVCaWtlTWVzc2FnZRIiCgxtYW51ZmFjdHVyZXIYASABKAlSDG1hbnVmYWN0dXJlchISCgRuYW1lGAIgA
  SgJUgRuYW1lEhYKBndlaWdodBgDIAEoAlIGd2VpZ2h0EhQKBXZhbHVlGAQgASgCUgV2YWx1ZRIlCgVwYXJ0cxgFIAMoCzIPLmJpa
  2VzLlBhcnRUeXBlUgVwYXJ0cyI2CghQYXJ0VHlwZRISCgRuYW1lGAEgASgJUgRuYW1lEhYKBndlaWdodBgCIAEoAlIGd2VpZ2h0I
  l8KD0FwcHJvdmFsTWVzc2FnZRIXCgdiaWtlX2lkGAEgASgDUgZiaWtlSWQSMwoIYXBwcm92YWwYAiABKA4yFy5iaWtlcy5BcHByb
  3ZhbEVudW1UeXBlUghhcHByb3ZhbCJDChJCaWtlQ3JlYXRlZE1lc3NhZ2USFwoHYmlrZV9pZBgBIAEoA1IGYmlrZUlkEhQKBXZhb
  HVlGAIgASgCUgV2YWx1ZSItChJCaWtlRGVsZXRlZE1lc3NhZ2USFwoHYmlrZV9pZBgBIAEoA1IGYmlrZUlkKjsKEEFwcHJvdmFsR
  W51bVR5cGUSCwoHUEVORElORxAAEgwKCEFDQ0VQVEVEEAESDAoIUkVKRUNURUQQAkIvCh1iaWtlcy5pbmZyYXN0cnVjdHVyZS5wc
  m90b2J1ZloOaW5mcmFzdHJ1Y3R1cmViBnByb3RvMw=="""
    ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, Array(
    ))
  }

  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}