// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package bikes.infrastructure.protobuf

@SerialVersionUID(0L)
final case class BikeCreatedMessage(
                                     bikeId: _root_.scala.Long = 0L,
                                     value: _root_.scala.Float = 0.0f
                                   ) extends scalapb.GeneratedMessage with scalapb.Message[BikeCreatedMessage] with scalapb.lenses.Updatable[BikeCreatedMessage] {
  @transient
  private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0

  private[this] def __computeSerializedValue(): _root_.scala.Int = {
    var __size = 0
    if (bikeId != 0L) {
      __size += _root_.com.google.protobuf.CodedOutputStream.computeInt64Size(1, bikeId)
    }
    if (value != 0.0f) {
      __size += _root_.com.google.protobuf.CodedOutputStream.computeFloatSize(2, value)
    }
    __size
  }

  final override def serializedSize: _root_.scala.Int = {
    var read = __serializedSizeCachedValue
    if (read == 0) {
      read = __computeSerializedValue()
      __serializedSizeCachedValue = read
    }
    read
  }

  def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): Unit = {
    {
      val __v = bikeId
      if (__v != 0L) {
        _output__.writeInt64(1, __v)
      }
    };
    {
      val __v = value
      if (__v != 0.0f) {
        _output__.writeFloat(2, __v)
      }
    };
  }

  def mergeFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): bikes.infrastructure.protobuf.BikeCreatedMessage = {
    var __bikeId = this.bikeId
    var __value = this.value
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 8 =>
          __bikeId = _input__.readInt64()
        case 21 =>
          __value = _input__.readFloat()
        case tag => _input__.skipField(tag)
      }
    }
    bikes.infrastructure.protobuf.BikeCreatedMessage(
      bikeId = __bikeId,
      value = __value
    )
  }

  def withBikeId(__v: _root_.scala.Long): BikeCreatedMessage = copy(bikeId = __v)

  def withValue(__v: _root_.scala.Float): BikeCreatedMessage = copy(value = __v)

  def getFieldByNumber(__fieldNumber: _root_.scala.Int): scala.Any = {
    (__fieldNumber: @_root_.scala.unchecked) match {
      case 1 => {
        val __t = bikeId
        if (__t != 0L) __t else null
      }
      case 2 => {
        val __t = value
        if (__t != 0.0f) __t else null
      }
    }
  }

  def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
    require(__field.containingMessage eq companion.scalaDescriptor)
    (__field.number: @_root_.scala.unchecked) match {
      case 1 => _root_.scalapb.descriptors.PLong(bikeId)
      case 2 => _root_.scalapb.descriptors.PFloat(value)
    }
  }

  def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)

  def companion = bikes.infrastructure.protobuf.BikeCreatedMessage
}

object BikeCreatedMessage extends scalapb.GeneratedMessageCompanion[bikes.infrastructure.protobuf.BikeCreatedMessage] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[bikes.infrastructure.protobuf.BikeCreatedMessage] = this

  def fromFieldsMap(__fieldsMap: scala.collection.immutable.Map[_root_.com.google.protobuf.Descriptors.FieldDescriptor, scala.Any]): bikes.infrastructure.protobuf.BikeCreatedMessage = {
    require(__fieldsMap.keys.forall(_.getContainingType() == javaDescriptor), "FieldDescriptor does not match message type.")
    val __fields = javaDescriptor.getFields
    bikes.infrastructure.protobuf.BikeCreatedMessage(
      __fieldsMap.getOrElse(__fields.get(0), 0L).asInstanceOf[_root_.scala.Long],
      __fieldsMap.getOrElse(__fields.get(1), 0.0f).asInstanceOf[_root_.scala.Float]
    )
  }

  implicit def messageReads: _root_.scalapb.descriptors.Reads[bikes.infrastructure.protobuf.BikeCreatedMessage] = _root_.scalapb.descriptors.Reads {
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
      bikes.infrastructure.protobuf.BikeCreatedMessage(
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Long]).getOrElse(0L),
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Float]).getOrElse(0.0f)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }

  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = BikesProto.javaDescriptor.getMessageTypes.get(5)

  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = BikesProto.scalaDescriptor.messages(5)

  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)

  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_]] = Seq.empty

  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)

  lazy val defaultInstance = bikes.infrastructure.protobuf.BikeCreatedMessage(
  )

  implicit class BikeCreatedMessageLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, bikes.infrastructure.protobuf.BikeCreatedMessage]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, bikes.infrastructure.protobuf.BikeCreatedMessage](_l) {
    def bikeId: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Long] = field(_.bikeId)((c_, f_) => c_.copy(bikeId = f_))

    def value: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Float] = field(_.value)((c_, f_) => c_.copy(value = f_))
  }

  final val BIKE_ID_FIELD_NUMBER = 1
  final val VALUE_FIELD_NUMBER = 2
}
